### ISSUE TITLE
2回目から失敗する

### ISSUE THREAD

**Issue by qaynam** [ThisIsSimmon/localhost-open-graph-debugger#15]
大変使いやすい拡張機能ありがとうございます。

多分バグかもしれませんが、一回目は成功しますが、2回目では👇エラーが出ます。

![image](https://user-images.githubusercontent.com/33139713/169305723-74494263-4d45-463d-96a5-fa699e40e25c.png)

**Comment by ThisIsSimmon** [comment]
先ほど上記のバグ修正したものを審査に出しましたので問題なければ数日以内に公開されると思います！
報告ありがとうございました！助かります🙏
